<?xml version="1.0"?>
<package format="3">
  <name>surface_perception_cpp</name>
  <version>0.1.0</version>
  <description>Modern C++17 ROS 2 defect-aware surface coverage planner.</description>
  <maintainer email="dewarajraparthi@gmail.com">Dewaraj Raparthi</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>diagnostic_msgs</depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
